channels:
  - conda-forge
  
dependencies:
  - python = 3.6 #Python packages
  - numpy
  - arrow
  - geopandas
  - pyshp
  - obspy
  - pandas
  - matplotlib
  - cryptography
  - geos
  - pillow
  - netCDF4
  - OWSLib 
  - basemap-data-hires
  - proj4
  - pyproj
  - pytz
  - brewer2mpl
  - jupyter
  - jupyter_client
  - ipykernel
  - jupyter_contrib_nbextensions
  - pip:
    - basemap
