name: GeoNet
channels:
  - conda-forge
dependencies:
  - cartopy
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - obspy == 1.1.0
  - cryptography
  - basemap == 1.1.0
  - proj4 
  - pyproj 
  - geos
  - pillow
  - nb_conda_kernels
