name: GeoNet
channels:
  - conda-forge
  - defaults
dependencies:
  - gcc
  - python = 3.6
  - r-base=3.4.1
  - r-dt
  - r-ggfortify
  - r-ggplot2
  - r-gsw
  - r-httr
  - r-lubridate
  - r-mapdata
  - r-ncdf4
  - r-oce
  - r-rcolorbrewer
  - r-rerddap
  - r-reshape2
  - r-sp
  - r-xtractomatic
  - r-xts
  - r-irkernel 
  - r-devtools
  - r-essentials
  - r-signal
  - r-timedate
  - r-jsonlite
  - r-Rcpp
  - r-RcppArmadillo
  - numpy
  - geopandas
  - pyshp
  - obspy
  - pandas
  - matplotlib
  - cryptography
  - geos
  - pillow
  - basemap = 1.1.0
  - proj4 = 4.9.3
  - pyproj = 1.9.5.1
  - jupyter
    ports:
    - 9000:900
  
