name: GeoNet
channels:
  - conda-forge
dependencies:
  - python = 3.6
  - r
  - r-irkernel 
  - r-essentials
  - r-signal
  - r-timedate
  - numpy
  - obspy
  - pandas
  - matplotlib
  - mpl_toolkits
  - cryptography
  - proj4
  - pyproj
  - basemap
  - jupyter
