name: GeoNet
channels:
  - conda-forge
dependencies:
  - gcc
  - python = 3.6
  - r
  - r-irkernel 
  - r-devtools
  - r-essentials
  - r-signal
  - r-timedate
  - r-jsonlite
  - r-Rcpp
  - r-RcppArmadillo
  - numpy
  - obspy
  - pandas
  - matplotlib
  - cryptography
  - geos
  - basemap = 1.1.0
  - proj4 = 4.9.3
  - pyproj = 1.9.5.1
  - jupyter
  - pip:
    - basemap
  
