name: GeoNet
channels:
  - conda-forge
dependencies:
  - python = 3.6
  - r
  - r-irkernel 
  - r-devtools
  - r-essentials
  - r-signal
  - r-timedate
  - r-jsonlite
  - r-Rcpp
  - r-RcppArmadillo
  - numpy
  - obspy
  - pandas
  - matplotlib
  - cryptography
  - proj4
  - pyproj
  - basemap
  - jupyter
environment:
    - "TZ=UTC" # offset = +00:00 -> Note, UTC does not have DST, also GMT has no DST!
ports:
    - 9000:900
