name: GeoNet
channels:
  - conda-forge
  - bioconda
  - bokeh
  - defaults
dependencies:
  - gcc
  - anaconda
  - python = 3.6
  - r-base=3.4.1 #R packages
  - r-dt
  - r-ggfortify
  - r-ggplot2
  - r-gsw
  - r-httr
  - r-lubridate
  - r-mapdata
  - r-ncdf4
  - r-oce
  - r-rcolorbrewer
  - r-rerddap
  - r-reshape2
  - r-sp
  - r-xtractomatic
  - r-xts
  - r-irkernel 
  - r-devtools
  - r-essentials
  - r-signal
  - r-timedate
  - r-jsonlite
  - r-Rcpp
  - r-RcppArmadillo
  - r-lubridate
  - numpy #Python packages
  - geopandas
  - pyshp
  - obspy
  - pandas
  - matplotlib
  - cryptography
  - geos
  - pillow
  - netCDF4
  - OWSLib 
  - basemap
  - basemap-data-hires
  - proj4
  - pyproj
  - jupyter
  
