name: GeoNet
channels:
  - conda-forge
dependencies:
  - python = 3.6
  - r
  - r-irkernel 
  - r-essentials
  - r-signal
  - TZ: "UCT"
  - pytz
  - numpy
  - obspy
  - pandas
  - matplotlib
  - geopandas
  - geos
  - proj4
  - pyproj 1.9.5.1
  - libxslt
  - basemap
  - jupyter
