name: GeoNet
channels:
  - conda-forge
dependencies:
  - cartopy
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - obspy == 1.1.0
  - cryptography
  - basemap == 1.1.0
  - proj4 == 4.9.3
  - pyproj == 1.9.5.1
  - basemap-data-hires
  - geos
  - pillow
  - nb_conda_kernels
