name: GeoNet
channels:
  - conda-forge
dependencies:
  - cartopy
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - obspy
  - cryptography
  - proj4 
  - pyproj 
  - geos
  - pillow
  - nb_conda_kernels
