name: GeoNet
channels:
  - conda-forge
dependencies:
  - python = 3.6
  - r
  - r-irkernel 
  - r-devtools
  - r-essentials
  - r-signal
  - r-timedate
  - r-jsonlite
  - r-Rcpp
  - r-RcppArmadillo
  - libgeos
  - libgeos-dev
  - numpy
  - obspy
  - pandas
  - matplotlib
  - cryptography
  - geos
  - proj4 = 5.1.0 
  - pyproj
  - basemap
  - jupyter
