name: GeoNet
channels:
  - conda-forge
  - defaults
dependencies:
  - gcc
  - anaconda
  - python = 3.6
  - r-base=3.4.1 #R packages
  - r-dt
  - r-ggfortify
  - r-ggplot2
  - r-gsw
  - r-httr
  - r-lubridate
  - r-mapdata
  - r-ncdf4
  - r-oce
  - r-rcolorbrewer
  - r-rerddap
  - r-reshape2
  - r-sp
  - r-xtractomatic
  - r-xts
  - r-irkernel 
  - r-devtools
  - r-essentials
  - r-signal
  - r-timedate
  - r-jsonlite
  - r-Rcpp
  - r-RcppArmadillo
  - r-lubridate
  - r-readxl
  - r-data.table
  - r-plyr
  - r-tidyr
  - r-openxlsx
  - numpy #Python packages
  - geopandas
  - pyshp
  - obspy
  - pandas
  - matplotlib
  - cryptography
  - geos
  - pillow
  - netCDF4
  - OWSLib 
  - basemap-data-hires
  - proj4
  - pyproj
  - brewer2mpl
  - jupyter
  - pip:
    - virtualenv
    - basemap
volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
  
