name: GeoNet
channels:
  - conda-forge
dependencies:
  - python = 3.6
  - r
  - r-irkernel 
  - r-essentials
  - r-signal
  - r-timedate
  - r-rprojroot
  - pytz
  - numpy
  - obspy
  - pandas
  - matplotlib
  - geopandas
  - geos
  - proj4
  - python-dateutil
  - pyproj
  - crypography
  - libsodium
  - matplotlib
  - matplotlib-base
  - basemap
  - jupyter
