name: GeoNet
channels:
  - conda-forge
dependencies:
  - python = 3.6
  - r
  - r-irkernel 
  - r-devtools
  - r-essentials
  - r-signal
  - r-timedate
  - r-jsonlite
  - r-Rcpp
  - r-RcppArmadillo
  - r-geojsonR
  - numpy
  - obspy
  - pandas
  - matplotlib
  - cryptography
  - proj4
  - pyproj
  - basemap
  - jupyter
