name: GeoNet
channels:
  - conda-forge
dependencies:
  - cartopy
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - obspy == 1.1.0
  - cryptography
  - geos
  - pillow
  - basemap
  - proj4
  - pyproj
